FROM golang:1.24-alpine as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o balancer ./Balancer/cmd/main.go

FROM alpine:3.19
WORKDIR /app

COPY --from=builder /app/balancer .
COPY Balancer/config/config.yaml .

EXPOSE 8080
CMD ["./balancer"]